# Generated by Django 3.2.4 on 2021-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text="Make sure the image is cropped to be square. You can use <a href='https://croppola.com/' target='_blank'>this external cropping tool</a>", null=True, upload_to='images/'),
        ),
    ]
