# Generated by Django 3.2.4 on 2021-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210824_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.MailingList'),
        ),
    ]
