# Generated by Django 3.2.4 on 2021-08-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_mailing_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contactable',
        ),
    ]
