# Generated by Django 3.2.4 on 2021-08-31 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210825_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('unsubscribe_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, help_text='This field is not required', max_length=200)),
            ],
            options={
                'verbose_name': 'Newsletter subscribers',
            },
        ),
    ]
