# Generated by Django 3.2.4 on 2021-10-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211008_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Member profiles'},
        ),
    ]
