# Generated by Django 3.2.4 on 2021-10-10 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211010_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unregister_key',
            field=models.UUIDField(null=True, default=uuid.uuid4, editable=False)
        ),
    ]
