# Generated by Django 3.2.4 on 2021-10-10 18:43

from django.db import migrations
import uuid


def populate_uuids(apps, schema_editor):
    MyModel = apps.get_model('user', 'Profile')
    for obj in MyModel.objects.all():
        obj.unregister_key = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20211010_1835'),
    ]

    operations = [
        migrations.RunPython(populate_uuids),
    ]
