# Generated by Django 3.2.4 on 2021-10-10 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20211010_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unregister_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
