# Generated by Django 3.2.4 on 2021-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20211010_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pics', verbose_name='Profile picture'),
        ),
    ]
