# Generated by Django 3.2.4 on 2021-10-12 15:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20211011_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submission_time',
            field=models.DateField("Time of submission", default=timezone.now)
        ),
    ]
