# Generated by Django 3.2.4 on 2021-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211012_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'Newsletter Subscriber'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Member profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_member',
            field=models.BooleanField(default=True, verbose_name='Show my profile on the site'),
        ),
    ]
