# Generated by Django 3.2.4 on 2021-10-15 19:17

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20211012_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='submission_time',
            field=models.DateTimeField("Time of submission", default=timezone.now)
        ),
    ]
