# Generated by Django 3.2.8 on 2021-10-15 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211015_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Time of submission'),
        ),
    ]
