# Generated by Django 3.2.8 on 2021-10-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_profile_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="submission_time"
        ),
    ]
