# Generated by Django 3.2.8 on 2021-10-15 20:52

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20211015_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submission_time',
            field=models.DateTimeField("Time of submission", default=timezone.now)
        ),
    ]
