# Generated by Django 3.2.8 on 2021-10-17 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20211016_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unregister_key',
            field=models.UUIDField(blank=False, default=uuid.uuid4, unique=True, editable=False)
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='unregister_key',
            new_name='registration_key',
        ),
    ]