# Generated by Django 3.2.8 on 2021-11-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20211017_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField("This email is automatically rejected at the door", default=False)
        ),
    ]