# Generated by Django 4.0 on 2022-01-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
