# Generated by Django 3.2.4 on 2021-07-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_accession', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('farm_name', models.CharField(blank=True, max_length=50)),
                ('farm_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('animal', models.CharField(blank=True, max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('antibiotics', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(blank=True, max_length=20)),
                ('age', models.FloatField(blank=True, null=True)),
                ('diet', models.CharField(blank=True, max_length=100)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.publication')),
            ],
        ),
    ]
