# Generated by Django 3.2.4 on 2021-08-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_publication_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data sets'},
        ),
        migrations.AlterField(
            model_name='data',
            name='publication',
            field=models.ForeignKey(blank=True, help_text="First author must be first and names must be separated with semicolon ';'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.publication'),
        ),
    ]
