# Generated by Django 3.2.4 on 2021-08-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20210801_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_type',
            field=models.CharField(default='undefined', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, help_text="First author must be first and names must be separated with semicolon ';'. <br>Example: <br>'Sapountzis, P.; Segura, A.; Desvaux, M.; Forano, E.'"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, help_text='Links are generated automatically from doi if one exists'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('peer-reviewed', 'peer-reviewed'), ('preprint', 'preprint')], max_length=20),
        ),
    ]
