# Generated by Django 3.2.4 on 2021-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210805_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='no_of_animals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='no_of_samples',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='target_region_16s',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
