# Generated by Django 3.2.4 on 2021-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20210806_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='FBP_detected',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='bioproject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
