# Generated by Django 4.1 on 2022-09-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_genome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.publication'),
        ),
    ]
