# Generated by Django 4.1 on 2022-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_genome_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
