# Generated by Django 4.1 on 2022-09-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_alter_genome_created_date_alter_genome_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.publication'),
        ),
    ]
