# Generated by Django 4.1 on 2022-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_alter_genome_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('current', models.BooleanField()),
                ('number', models.SmallIntegerField()),
                ('genomes', models.ManyToManyField(to='resources.genome')),
            ],
        ),
    ]
