# Generated by Django 4.1 on 2022-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_genome_version_genomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='version',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
